/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppBusinessIndexRouteImport } from './routes/_app/business/index'
import { Route as AppDesignIndexRouteImport } from './routes/_app/design/index'
import { Route as AppEditingIndexRouteImport } from './routes/_app/editing/index'
import { Route as AppMarketIndexRouteImport } from './routes/_app/market/index'
import { Route as AppOverviewIndexRouteImport } from './routes/_app/overview/index'
import { Route as AppOverviewCalendarRouteImport } from './routes/_app/overview/calendar'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsFeishuRouteImport } from './routes/_app/settings/feishu'
import { Route as AppMarketEventsEventIdRouteImport } from './routes/_app/market/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppBusinessIndexRoute = AppBusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignIndexRoute = AppDesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => AppRoute,
} as any)
const AppEditingIndexRoute = AppEditingIndexRouteImport.update({
  id: '/editing/',
  path: '/editing/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewIndexRoute = AppOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewCalendarRoute = AppOverviewCalendarRouteImport.update({
  id: '/overview/calendar',
  path: '/overview/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsFeishuRoute = AppSettingsFeishuRouteImport.update({
  id: '/settings/feishu',
  path: '/settings/feishu',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketEventsEventIdRoute = AppMarketEventsEventIdRouteImport.update({
  id: '/market/events/$eventId',
  path: '/market/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/overview/calendar': typeof AppOverviewCalendarRoute
  '/settings/feishu': typeof AppSettingsFeishuRoute
  '/business/': typeof AppBusinessIndexRoute
  '/design/': typeof AppDesignIndexRoute
  '/editing/': typeof AppEditingIndexRoute
  '/market/': typeof AppMarketIndexRoute
  '/overview/': typeof AppOverviewIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/market/events/$eventId': typeof AppMarketEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/overview/calendar': typeof AppOverviewCalendarRoute
  '/settings/feishu': typeof AppSettingsFeishuRoute
  '/business': typeof AppBusinessIndexRoute
  '/design': typeof AppDesignIndexRoute
  '/editing': typeof AppEditingIndexRoute
  '/market': typeof AppMarketIndexRoute
  '/overview': typeof AppOverviewIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/market/events/$eventId': typeof AppMarketEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/overview/calendar': typeof AppOverviewCalendarRoute
  '/_app/settings/feishu': typeof AppSettingsFeishuRoute
  '/_app/business/': typeof AppBusinessIndexRoute
  '/_app/design/': typeof AppDesignIndexRoute
  '/_app/editing/': typeof AppEditingIndexRoute
  '/_app/market/': typeof AppMarketIndexRoute
  '/_app/overview/': typeof AppOverviewIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/market/events/$eventId': typeof AppMarketEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/login'
    | '/overview/calendar'
    | '/settings/feishu'
    | '/business/'
    | '/design/'
    | '/editing/'
    | '/market/'
    | '/overview/'
    | '/settings/'
    | '/market/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/login'
    | '/overview/calendar'
    | '/settings/feishu'
    | '/business'
    | '/design'
    | '/editing'
    | '/market'
    | '/overview'
    | '/settings'
    | '/market/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/search'
    | '/_auth/login'
    | '/_app/overview/calendar'
    | '/_app/settings/feishu'
    | '/_app/business/'
    | '/_app/design/'
    | '/_app/editing/'
    | '/_app/market/'
    | '/_app/overview/'
    | '/_app/settings/'
    | '/_app/market/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/business/': {
      id: '/_app/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof AppBusinessIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design/': {
      id: '/_app/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof AppDesignIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/editing/': {
      id: '/_app/editing/'
      path: '/editing'
      fullPath: '/editing/'
      preLoaderRoute: typeof AppEditingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market/': {
      id: '/_app/market/'
      path: '/market'
      fullPath: '/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview/': {
      id: '/_app/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AppOverviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview/calendar': {
      id: '/_app/overview/calendar'
      path: '/overview/calendar'
      fullPath: '/overview/calendar'
      preLoaderRoute: typeof AppOverviewCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/feishu': {
      id: '/_app/settings/feishu'
      path: '/settings/feishu'
      fullPath: '/settings/feishu'
      preLoaderRoute: typeof AppSettingsFeishuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market/events/$eventId': {
      id: '/_app/market/events/$eventId'
      path: '/market/events/$eventId'
      fullPath: '/market/events/$eventId'
      preLoaderRoute: typeof AppMarketEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppOverviewCalendarRoute: typeof AppOverviewCalendarRoute
  AppSettingsFeishuRoute: typeof AppSettingsFeishuRoute
  AppBusinessIndexRoute: typeof AppBusinessIndexRoute
  AppDesignIndexRoute: typeof AppDesignIndexRoute
  AppEditingIndexRoute: typeof AppEditingIndexRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppOverviewIndexRoute: typeof AppOverviewIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppMarketEventsEventIdRoute: typeof AppMarketEventsEventIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppOverviewCalendarRoute: AppOverviewCalendarRoute,
  AppSettingsFeishuRoute: AppSettingsFeishuRoute,
  AppBusinessIndexRoute: AppBusinessIndexRoute,
  AppDesignIndexRoute: AppDesignIndexRoute,
  AppEditingIndexRoute: AppEditingIndexRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppOverviewIndexRoute: AppOverviewIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppMarketEventsEventIdRoute: AppMarketEventsEventIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
